name: GitHub Actions Demo

on: [push]

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if { [ 'itg2' = 'itg1' ] || [ 'itg1' = 'itg1' ] } && { [ 'test' = 'hoge' ] || [ 'test' = 'test' ] }; then 
            echo "true"
          else
            echo "false"
          fi
