name: GitHub Actions Demo

on: [push]

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world!!"
          if [ "true" = "false" || "true" = "true" ]; then 
            if [ "test" = "test" ];
              then echo "true"
            else
              echo "false"
            fi
          fi
